export const OFFICIAL_META_CITIES = [
  "Massa",
  "Mirleft",
  "Oulad Berhil",
  "Oulad Dahou",
  "Sebt El Guerdane",
  "Sidi bibi",
  "SIDI IFNI",
  "Temsia",
  "Taroudant",
  "Tarrast",
  "TATA",
  "Tin Mansour",
  "Tiznit",
  "Dakhla",
  "Boujdour",
  "Essmara SAHARA",
  "Guelmim",
  "laayoune Port",
  "Laayoune Sahara",
  "Bouizakarne",
  "TANTAN",
  "Oulad Teima",
  "IFRANE",
  "Ougmas",
  "Sidi Jaber",
  "Oulad Ayad",
  "Timoulilte",
  "Azilal",
  "Aguelmous",
  "Oued Zem",
  "Kasba Tadla",
  "Ouled Nemma",
  "Ouled Mbarek",
  "Khenifra",
  "Khouribga",
  "Tighssaline",
  "Bejaad",
  "El Ksiba - Beni-Mellal",
  "Ighrem Laalam",
  "Fquih Ben Salah",
  "Oulad zmam",
  "Dar Ould Zidouh",
  "Sidi Aissa Ben Ali",
  "Bni Ayat",
  "Mrirt",
  "Ait Ishaq",
  "Laayayta - Beni Mellal",
  "Ouaouizeght",
  "Ouaoumana",
  "Oulad Yaich",
  "Oulad Youssef - Beni Mellal",
  "Ikhourba",
  "AZROU",
  "Ayt Yahya Oalla",
  "Ait Ali Azrou",
  "Oulad Ali - Beni Mellal",
  "Foum Oudi - Beni Mellal",
  "Kahf Nsour",
  "Dar Oulad Zidouh",
  "Ahl Merbaa - Beni Mellal",
  "Ahl Souss - Beni Mellal",
  "Ain El Ghazi Ali - Beni Mellal",
  "Ait Attab",
  "Ait Tislit",
  "Aourir - Beni Mellal",
  "Bir Mezoui",
  "El Bazzaza",
  "El Kbab",
  "Faryata",
  "Foum El Anser",
  "Foum Jamaa",
  "Foum Zaouia",
  "Had Bouhsousen",
  "Ikhoureba - Beni Mellal",
  "Kahf Nssoure",
  "Laajana",
  "Laayayta Oulad Gnaou",
  "Lahlalma",
  "Lakraza Ouled Said",
  "Mghila - Beni Mellal",
  "Moulay Bouaza",
  "Oulad Ali Loued",
  "Oulad Moussa - Beni Mellal",
  "Ouled Rguiaa",
  "Ouzoud - Beni Mellal",
  "Riad Salam-Beni Mellal",
  "Tanant",
  "Tifrit - Beni Mellal",
  "Tighasaline",
  "Zone Industriell - Beni Mellal",
  "Zouair",
  "Boulemane",
  "Guigou",
  "Casablanca",
  "had soualem",
  "Mohammedia",
  "Almaz",
  "Benslimane",
  "Berrchid",
  "Bouskoura",
  "Bouznika",
  "Dar Bouazza",
  "Errahma",
  "Mediouna",
  "Nouaceur",
  "Settat",
  "Tit Mellil",
  "Dar 16",
  "Deroua",
  "Lahraouyine",
  "La ville verte",
  "Lamkansa - Casa",
  "Sidi Massoud",
  "Ain Harrouda",
  "Ben ahmed",
  "Plage David Bouznika",
  "Ben Yakhlef",
  "Lkhyayta - Had soualem",
  "Lakhyayeta",
  "Mqam Tolba",
  "El Jadida",
  "Sidi Bouzid SAFI",
  "Sidi Bouzid El Jadida",
  "El Haouzia",
  "Sidi Bennour",
  "Khemis Zemamera",
  "Azemmour",
  "Bir Jdid",
  "Tnine Chtouka El jadida",
  "Oualidia",
  "Sidi Abbad",
  "Oulad Frej",
  "Zaouit Sidi Smail",
  "Jorf Lasfar",
  "Tnine Gharbia",
  "Sidi Abderrazzak Khzazna",
  "Sidi Addi",
  "Timahdite",
  "Oulad Amrane",
  "Moulay Abellah Amghar",
  "Sidi Ali Azemmour",
  "Oulad Ghanem",
  "Arba Aounate",
  "Safi",
  "Sebt Gzoula",
  "Jamaat shaim",
  "Hrara Safi",
  "Had Hrara- Safi",
  "Smimou",
  "Ain Allah",
  "Ain Bida",
  "Ain Cheggag",
  "Ain Taoujdate",
  "MHAYA - MEKNES",
  "Moulay Yacoub",
  "Sidi Harazem",
  "Kariat Ba Mohamed",
  "KHEMISSET",
  "Maaziz",
  "Oulmes",
  "Rommani",
  "Sidi Allal El Bahraoui",
  "Tiddas",
  "TIFLET",
  "Jamaa Houderrane",
  "Ait Belkacem",
  "Chellalat",
  "Sidi Hajjaj",
  "Marrakech",
  "Ait Ourir",
  "Tahannaout",
  "Agadir",
  "Aglou",
  "Ait Amira",
  "Ait Baha",
  "Ait melloul",
  "Anza",
  "Aourir",
  "Belfaa",
  "Biougra",
  "Akka",
  "Aoulouz",
  "Fam El Hisn",
  "Foum zguid",
  "Houara",
  "Imi Ouaddar",
  "Inchaden",
  "Inezgane",
  "Tameslohte",
  "Ben Guerir",
  "El Kelaa des Sraghna",
  "Chichaoua",
  "imintanoute",
  "Youssoufia",
  "Tamansourt",
  "Souihla",
  "Chouiter",
  "Sidi Abdellah Ghiat",
  "OUDAYA Marrakech",
  "Sid L Mokhtar",
  "Tamellalt",
  "Belaaguid",
  "Mejjat - Marrakech",
  "Sidi Bou Othmane",
  "El Attaouia",
  "Echemmaia",
  "Skhour Rehamna",
  "Mzoudia",
  "Ouahat Sidi Brahim",
  "Sid Zouine",
  "Ourika",
  "Lalla Takerkoust",
  "Amizmiz",
  "Tassoultante",
  "OULED BEN RAHMOUN",
  "Gouassem",
  "Taznakht",
  "Asni",
  "Ouidane MARRAKECH",
  "OULAD HASSOUN",
  "Nzalat Laadam",
  "Sebt Saiss",
  "Moulay Brahim",
  "Douar Sidi Moussa",
  "Oulad yahya",
  "Douar Soultan",
  "Douar Bouazza",
  "Chrifia",
  "loudaya",
  "Dcheira",
  "Tikiouine",
  "Drarga",
  "Assa",
  "Lagfifat",
  "Kasbah El Taher",
  "Bounaamane - Tiznit",
  "Tarfaya",
  "Essaouira",
  "Agdz",
  "Nkoub Zagora",
  "Tazarine",
  "Ouarzazate",
  "Tinghir",
  "Boumaln dads",
  "Alnif",
  "Kelaat MGouna",
  "Tissint",
  "Akka Ighane",
  "Tazenakht",
  "Ghazoua",
  "Douar Laareb",
  "Sidi Kaouki",
  "Ounagha",
  "Al Morabitin",
  "Kchoula",
  "Ain Leuh",
  "Agourai",
  "AIN KARMA",
  "AIT YAAZEM",
  "BOUDERBALA",
  "Boufakrane",
  "BRIDIA",
  "DKHISSA",
  "EL BARAKA - MEKNES",
  "ELHajeb",
  "Haj Kaddour",
  "MEJJAT - Meknes",
  "Ait Said",
  "Bizdad",
  "Meskala",
  "Mejji",
  "Had Draa",
  "Tidzi",
  "Sidi Boulaalam",
  "Boulaalam",
  "Birkouate",
  "Lwaiha",
  "Faj Errih",
  "Kraymat",
  "Mramer",
  "AKHFNIR",
  "MEKNES",
  "Moulay Idriss Zerhoun",
  "OUED JDIDA",
  "OUISSLAN",
  "Sabaâ Aïyoun - MEKNES",
  "Ain jiri - meknes",
  "Missour",
  "Outat El Haj",
  "Imouzzer Marmoucha",
  "Oujda",
  "NADOR",
  "Beni Ensar",
  "Selouane",
  "Ouled Said El Oued",
  "Kaf Nsour",
  "Hattane",
  "Boujniba",
  "Boulanouare",
  "Ouled Driss - Beni Mellal",
  "Al Khalfia",
  "Ouled Mrah",
  "Oulad ismail - Beni Mellal",
  "Ait Ali",
  "Ait Rbaa",
  "Tanougha",
  "Adouz - Beni Mellal",
  "Aghbalou Ncerdan",
  "Ouled Moussa",
  "El Borj - Khenifra",
  "Lahri - khenifra",
  "Demnate",
  "Beni Mellal",
  "Jaadar",
  "Zeghanghane",
  "Segangan",
  "AFRA",
  "Al Aaroui",
  "Bouarg",
  "Mariouari",
  "Barichino",
  "Tiztoutine",
  "Beni Chiker",
  "Farkhana",
  "Beni Sidal Jbel",
  "Kariat Arekmane",
  "Zaio",
  "Ouled Settout",
  "Driouch",
  "Ben Taieb",
  "Tafersit",
  "Midar",
  "Kassita",
  "Telat Azlaf",
  "Tamsamane",
  "Boudinar",
  "Dar El Kebdani",
  "Berkane",
  "AHFIR",
  "Ain Erreggada",
  "Ain Reggada",
  "Aklim",
  "Boughriba",
  "Madagh",
  "SAAIDIA",
  "Saidia",
  "Beni Drar",
  "Jerada",
  "Ain Beni Mathar",
  "Tendrara",
  "Bouarfa",
  "Figuig",
  "Laayoune Charkia",
  "El Aioun Sidi Mellouk",
  "Taourirt",
  "Guercif",
  "Tafoughalt",
  "Ras El Ma - Nador",
  "Dlalha",
  "Jorf El Melha",
  "Khenichet",
  "Lalla mimouna",
  "Mechra Bel Ksiri",
  "Moulay Bousselham",
  "RABAT",
  "Sidi Kacem",
  "Sidi slimane",
  "Sidi Yahya El Gharb",
  "SOUK LARBAA",
  "El Arjate",
  "Sale",
  "Sala Al Jadida",
  "Temara",
  "Tamesna",
  "Skhirat",
  "Ain Attig",
  "Ain El Aouda",
  "Sidi Yahya Zaer",
  "Harhoura",
  "Mers El Kheir",
  "Sidi Bouknadel",
  "Kenitra",
  "Sidi Taibi",
  "Mehdia",
  "Sidi Allal Tazi",
  "El Khemis des Aït Ouahi",
  "El Ouatia TAN TAN",
  "Zagora",
  "Zag",
  "El Hrarta",
  "El Hanchane",
  "EL MARSA LAAYOUNE",
  "Afourar",
  "Zaouiat Cheikh",
  "El Kebab",
  "El Gara",
  "El Mansouria",
  "El Borouj",
  "Zenata",
  "Ras El Ma-FES",
  "Ain Chkef - FES",
  "Douiyat - FES",
  "FES",
  "Imouzzer-Kandar - FES",
  "Oulad Tayeb - FES",
  "Bhalil",
  "El Menzel - SEFROU",
  "Ribate El Kheir",
  "Sefrou",
  "Azzaba - Sefrou",
  "Zaouiat Bougrine - Sefrou",
  "Senhaja - Sefrou",
  "Bir Tam Tam",
  "Ras Tabouda",
  "Boudnib",
  "Marzouga",
  "Zaida",
  "Tinejdad",
  "Rissani",
  "Riche",
  "Boumia",
  "Erfoud",
  "Errachidia",
  "Goulmima - Errachidia",
  "Aoufous",
  "Msemrir tinghir",
  "Midelt",
  "Gourrama",
  "Imilchil",
  "Ouazzane",
  "Tanger",
  "Martil",
  "Cabo Negro",
  "Marina smir",
  "Kabila",
  "Bouzaghlal",
  "Bni Rzine",
  "bouanane tetouan",
  "Bab Berred",
  "Asilah",
  "Bab Taza",
  "Chefchaouen",
  "Fnideq",
  "El Jebeha",
  "M Diq",
  "Larache",
  "Ksar Sghir",
  "Oued Laou",
  "Tetouan",
  "Ksar El Kebir",
  "Ain dorij",
  "Zoumi",
  "Gueznaia",
  "Azla",
  "El aanssar",
  "Khamis Mdiq",
  "Ounnana",
  "Brikcha",
  "Belyounech",
  "Teroual - Ouazzane",
  "Targuist",
  "Issaguen",
  "kaa asras",
  "Amsa",
  "Stehat",
  "Ghafsai",
  "Taounate",
  "Kantra El Ascar",
  "Zrizer",
  "khlalfa",
  "sebt mtiwa",
  "Beni Oulid",
  "Bouhouda",
  "Mernissa",
  "Thar Es-Souk",
  "Fricha - Taounate",
  "Tafraoute",
  "Taghazout",
  "Taliouine",
  "Tamraght",
  "Taddart - Agadir",
  "Tagounite\u202c zagora",
  "Smara",
  "Tafetachte",
  "Tamanar",
  "Talmest",
  "Tamzmout",
  "Tagzert",
  "Souk El Had Des Bradia",
  "Souk Sebt Oulad Nemma",
  "Tachrafat",
  "Sidi Rahal",
  "Tamaris",
  "Skhinate",
  "SOUK EL GOUR",
  "Tandit",
  "El Aouamra",
  "Dalia",
  "Beni Ahmed - Chefchaouen",
  "Dardara",
  "Akchour",
  "Dar Akoubaa",
  "Ametrass",
  "Al Hoceima",
  "Imzouren",
  "Bni Bouayach",
  "Ait youssef",
  "Ain Defali",
  "Ain Beida - Ouazzane",
  "Masmouda",
  "Sidi Bousber",
  "Sidi Redouane",
  "Mokrisset",
  "Souk Khemis du Sahel",
  "Louizia",
  "Ourtzagh - Taounate",
  "Sahel Boutaher - Taounate",
  "Galaz - Taounate",
  "Ain Mediouna - Taounate",
  "Ain Aicha",
  "Ouled Daoud - Taounate",
  "Tissa",
  "Ain Kansara",
  "Oued Amlil",
  "TAHLA",
  "TAZA",
  "Ajdir",
  "Bab Marzouka",
  "Taddart - Taza",
  "Aknoul",
  "Tizi Ouasli",
] as const;

export type OfficialMetaCity = (typeof OFFICIAL_META_CITIES)[number];

export const FALLBACK_META_CITY = "RABAT";
export const OFFICIAL_META_CITY_SET = new Set<string>(OFFICIAL_META_CITIES);

export function isOfficialMetaCity(value: string) {
  return OFFICIAL_META_CITY_SET.has((value || "").trim());
}

export function hasArabic(value: string) {
  return /[\u0600-\u06ff]/.test(value || "");
}

export function filterOfficialMetaCities(query: string, limit = 40) {
  const q = (query || "").trim().toLowerCase();
  if (!q) return OFFICIAL_META_CITIES.slice(0, limit);
  const hits: string[] = [];
  for (const city of OFFICIAL_META_CITIES) {
    if (city.toLowerCase().includes(q) || city.split(" - ")[0].toLowerCase().includes(q)) {
      hits.push(city);
      if (hits.length >= limit) break;
    }
  }
  return hits;
}
