export const REGION_NAME_TO_ID: Record<string, string> = {
  "طنجة - تطوان - الحسيمة": "MA01",
  "الشرق": "MA02",
  "فاس - مكناس": "MA03",
  "الرباط - سلا - القنيطرة": "MA04",
  "بني ملال - خنيفرة": "MA05",
  "الدار البيضاء - سطات": "MA06",
  "مراكش - آسفي": "MA07",
  "درعة - تافيلالت": "MA08",
  "سوس - ماسة": "MA09",
  "كلميم - واد نون": "MA10",
  "العيون - الساقية الحمراء": "MA11",
  "الداخلة - وادي الذهب": "MA12",
};

export const UNKNOWN_REGION = "غير محددة";

export const CITY_TO_REGION: Record<string, string> = {
  "Tanger": "طنجة - تطوان - الحسيمة",
  "Tetouan": "طنجة - تطوان - الحسيمة",
  "Martil": "طنجة - تطوان - الحسيمة",
  "Cabo Negro": "طنجة - تطوان - الحسيمة",
  "Marina smir": "طنجة - تطوان - الحسيمة",
  "Kabila": "طنجة - تطوان - الحسيمة",
  "Bouzaghlal": "طنجة - تطوان - الحسيمة",
  "Bni Rzine": "طنجة - تطوان - الحسيمة",
  "bouanane tetouan": "طنجة - تطوان - الحسيمة",
  "Bab Berred": "طنجة - تطوان - الحسيمة",
  "Asilah": "طنجة - تطوان - الحسيمة",
  "Bab Taza": "طنجة - تطوان - الحسيمة",
  "Chefchaouen": "طنجة - تطوان - الحسيمة",
  "Fnideq": "طنجة - تطوان - الحسيمة",
  "El Jebeha": "طنجة - تطوان - الحسيمة",
  "M Diq": "طنجة - تطوان - الحسيمة",
  "Khamis Mdiq": "طنجة - تطوان - الحسيمة",
  "Larache": "طنجة - تطوان - الحسيمة",
  "Ksar Sghir": "طنجة - تطوان - الحسيمة",
  "Oued Laou": "طنجة - تطوان - الحسيمة",
  "Ksar El Kebir": "طنجة - تطوان - الحسيمة",
  "Ain dorij": "طنجة - تطوان - الحسيمة",
  "Zoumi": "طنجة - تطوان - الحسيمة",
  "Gueznaia": "طنجة - تطوان - الحسيمة",
  "Azla": "طنجة - تطوان - الحسيمة",
  "El aanssar": "طنجة - تطوان - الحسيمة",
  "Ounnana": "طنجة - تطوان - الحسيمة",
  "Brikcha": "طنجة - تطوان - الحسيمة",
  "Belyounech": "طنجة - تطوان - الحسيمة",
  "Teroual - Ouazzane": "طنجة - تطوان - الحسيمة",
  "Ouazzane": "طنجة - تطوان - الحسيمة",
  "Targuist": "طنجة - تطوان - الحسيمة",
  "Issaguen": "طنجة - تطوان - الحسيمة",
  "kaa asras": "طنجة - تطوان - الحسيمة",
  "Amsa": "طنجة - تطوان - الحسيمة",
  "Stehat": "طنجة - تطوان - الحسيمة",
  "sebt mtiwa": "طنجة - تطوان - الحسيمة",
  "Beni Ahmed - Chefchaouen": "طنجة - تطوان - الحسيمة",
  "Dardara": "طنجة - تطوان - الحسيمة",
  "Akchour": "طنجة - تطوان - الحسيمة",
  "Dar Akoubaa": "طنجة - تطوان - الحسيمة",
  "Ametrass": "طنجة - تطوان - الحسيمة",
  "Al Hoceima": "طنجة - تطوان - الحسيمة",
  "Imzouren": "طنجة - تطوان - الحسيمة",
  "Bni Bouayach": "طنجة - تطوان - الحسيمة",
  "Ait youssef": "طنجة - تطوان - الحسيمة",
  "Ain Defali": "طنجة - تطوان - الحسيمة",
  "Ain Beida - Ouazzane": "طنجة - تطوان - الحسيمة",
  "Masmouda": "طنجة - تطوان - الحسيمة",
  "Sidi Bousber": "طنجة - تطوان - الحسيمة",
  "Sidi Redouane": "طنجة - تطوان - الحسيمة",
  "Mokrisset": "طنجة - تطوان - الحسيمة",
  "Souk Khemis du Sahel": "طنجة - تطوان - الحسيمة",
  "El Aouamra": "طنجة - تطوان - الحسيمة",
  "Dalia": "طنجة - تطوان - الحسيمة",
  "FES": "فاس - مكناس",
  "MEKNES": "فاس - مكناس",
  "Ain Allah": "فاس - مكناس",
  "Ain Bida": "فاس - مكناس",
  "Ain Cheggag": "فاس - مكناس",
  "Ain Taoujdate": "فاس - مكناس",
  "MHAYA - MEKNES": "فاس - مكناس",
  "Moulay Yacoub": "فاس - مكناس",
  "Sidi Harazem": "فاس - مكناس",
  "Kariat Ba Mohamed": "فاس - مكناس",
  "Ain Leuh": "فاس - مكناس",
  "Agourai": "فاس - مكناس",
  "AIN KARMA": "فاس - مكناس",
  "AIT YAAZEM": "فاس - مكناس",
  "BOUDERBALA": "فاس - مكناس",
  "Boufakrane": "فاس - مكناس",
  "BRIDIA": "فاس - مكناس",
  "DKHISSA": "فاس - مكناس",
  "EL BARAKA - MEKNES": "فاس - مكناس",
  "ELHajeb": "فاس - مكناس",
  "Haj Kaddour": "فاس - مكناس",
  "MEJJAT - Meknes": "فاس - مكناس",
  "Moulay Idriss Zerhoun": "فاس - مكناس",
  "OUED JDIDA": "فاس - مكناس",
  "OUISSLAN": "فاس - مكناس",
  "Sabaâ Aïyoun - MEKNES": "فاس - مكناس",
  "Ain jiri - meknes": "فاس - مكناس",
  "Boulemane": "فاس - مكناس",
  "Guigou": "فاس - مكناس",
  "Missour": "فاس - مكناس",
  "Outat El Haj": "فاس - مكناس",
  "Imouzzer Marmoucha": "فاس - مكناس",
  "IFRANE": "فاس - مكناس",
  "AZROU": "فاس - مكناس",
  "Ayt Yahya Oalla": "فاس - مكناس",
  "Ait Ali Azrou": "فاس - مكناس",
  "Sidi Addi": "فاس - مكناس",
  "Timahdite": "فاس - مكناس",
  "Ras El Ma-FES": "فاس - مكناس",
  "Ain Chkef - FES": "فاس - مكناس",
  "Douiyat - FES": "فاس - مكناس",
  "Imouzzer-Kandar - FES": "فاس - مكناس",
  "Oulad Tayeb - FES": "فاس - مكناس",
  "Bhalil": "فاس - مكناس",
  "El Menzel - SEFROU": "فاس - مكناس",
  "Ribate El Kheir": "فاس - مكناس",
  "Sefrou": "فاس - مكناس",
  "Azzaba - Sefrou": "فاس - مكناس",
  "Zaouiat Bougrine - Sefrou": "فاس - مكناس",
  "Senhaja - Sefrou": "فاس - مكناس",
  "Bir Tam Tam": "فاس - مكناس",
  "Ras Tabouda": "فاس - مكناس",
  "Ghafsai": "فاس - مكناس",
  "Taounate": "فاس - مكناس",
  "Kantra El Ascar": "فاس - مكناس",
  "Zrizer": "فاس - مكناس",
  "khlalfa": "فاس - مكناس",
  "Beni Oulid": "فاس - مكناس",
  "Bouhouda": "فاس - مكناس",
  "Mernissa": "فاس - مكناس",
  "Thar Es-Souk": "فاس - مكناس",
  "Fricha - Taounate": "فاس - مكناس",
  "Ourtzagh - Taounate": "فاس - مكناس",
  "Sahel Boutaher - Taounate": "فاس - مكناس",
  "Galaz - Taounate": "فاس - مكناس",
  "Ain Mediouna - Taounate": "فاس - مكناس",
  "Ain Aicha": "فاس - مكناس",
  "Ouled Daoud - Taounate": "فاس - مكناس",
  "Tissa": "فاس - مكناس",
  "Ain Kansara": "فاس - مكناس",
  "Oued Amlil": "فاس - مكناس",
  "TAHLA": "فاس - مكناس",
  "TAZA": "فاس - مكناس",
  "Ajdir": "فاس - مكناس",
  "Bab Marzouka": "فاس - مكناس",
  "Taddart - Taza": "فاس - مكناس",
  "Aknoul": "فاس - مكناس",
  "Tizi Ouasli": "فاس - مكناس",
  "Skhinate": "فاس - مكناس",
  "RABAT": "الرباط - سلا - القنيطرة",
  "Sale": "الرباط - سلا - القنيطرة",
  "Sala Al Jadida": "الرباط - سلا - القنيطرة",
  "Temara": "الرباط - سلا - القنيطرة",
  "Tamesna": "الرباط - سلا - القنيطرة",
  "Skhirat": "الرباط - سلا - القنيطرة",
  "Ain Attig": "الرباط - سلا - القنيطرة",
  "Ain El Aouda": "الرباط - سلا - القنيطرة",
  "Sidi Yahya Zaer": "الرباط - سلا - القنيطرة",
  "Harhoura": "الرباط - سلا - القنيطرة",
  "Mers El Kheir": "الرباط - سلا - القنيطرة",
  "Sidi Bouknadel": "الرباط - سلا - القنيطرة",
  "El Arjate": "الرباط - سلا - القنيطرة",
  "Kenitra": "الرباط - سلا - القنيطرة",
  "Sidi Taibi": "الرباط - سلا - القنيطرة",
  "Mehdia": "الرباط - سلا - القنيطرة",
  "Sidi Allal Tazi": "الرباط - سلا - القنيطرة",
  "Sidi Kacem": "الرباط - سلا - القنيطرة",
  "Sidi slimane": "الرباط - سلا - القنيطرة",
  "Sidi Yahya El Gharb": "الرباط - سلا - القنيطرة",
  "SOUK LARBAA": "الرباط - سلا - القنيطرة",
  "Dlalha": "الرباط - سلا - القنيطرة",
  "Jorf El Melha": "الرباط - سلا - القنيطرة",
  "Khenichet": "الرباط - سلا - القنيطرة",
  "Lalla mimouna": "الرباط - سلا - القنيطرة",
  "Mechra Bel Ksiri": "الرباط - سلا - القنيطرة",
  "Moulay Bousselham": "الرباط - سلا - القنيطرة",
  "KHEMISSET": "الرباط - سلا - القنيطرة",
  "Maaziz": "الرباط - سلا - القنيطرة",
  "Oulmes": "الرباط - سلا - القنيطرة",
  "Rommani": "الرباط - سلا - القنيطرة",
  "Sidi Allal El Bahraoui": "الرباط - سلا - القنيطرة",
  "Tiddas": "الرباط - سلا - القنيطرة",
  "TIFLET": "الرباط - سلا - القنيطرة",
  "Jamaa Houderrane": "الرباط - سلا - القنيطرة",
  "Ait Belkacem": "الرباط - سلا - القنيطرة",
  "Mqam Tolba": "الرباط - سلا - القنيطرة",
  "El Khemis des Aït Ouahi": "الرباط - سلا - القنيطرة",
  "Casablanca": "الدار البيضاء - سطات",
  "had soualem": "الدار البيضاء - سطات",
  "Mohammedia": "الدار البيضاء - سطات",
  "Almaz": "الدار البيضاء - سطات",
  "Benslimane": "الدار البيضاء - سطات",
  "Berrchid": "الدار البيضاء - سطات",
  "Bouskoura": "الدار البيضاء - سطات",
  "Bouznika": "الدار البيضاء - سطات",
  "Dar Bouazza": "الدار البيضاء - سطات",
  "Errahma": "الدار البيضاء - سطات",
  "Mediouna": "الدار البيضاء - سطات",
  "Nouaceur": "الدار البيضاء - سطات",
  "Settat": "الدار البيضاء - سطات",
  "Tit Mellil": "الدار البيضاء - سطات",
  "Dar 16": "الدار البيضاء - سطات",
  "Deroua": "الدار البيضاء - سطات",
  "Lahraouyine": "الدار البيضاء - سطات",
  "La ville verte": "الدار البيضاء - سطات",
  "Lamkansa - Casa": "الدار البيضاء - سطات",
  "Sidi Massoud": "الدار البيضاء - سطات",
  "Ain Harrouda": "الدار البيضاء - سطات",
  "Ben ahmed": "الدار البيضاء - سطات",
  "Plage David Bouznika": "الدار البيضاء - سطات",
  "Ben Yakhlef": "الدار البيضاء - سطات",
  "Lkhyayta - Had soualem": "الدار البيضاء - سطات",
  "Lakhyayeta": "الدار البيضاء - سطات",
  "El Jadida": "الدار البيضاء - سطات",
  "Sidi Bouzid El Jadida": "الدار البيضاء - سطات",
  "El Haouzia": "الدار البيضاء - سطات",
  "Sidi Bennour": "الدار البيضاء - سطات",
  "Khemis Zemamera": "الدار البيضاء - سطات",
  "Azemmour": "الدار البيضاء - سطات",
  "Bir Jdid": "الدار البيضاء - سطات",
  "Tnine Chtouka El jadida": "الدار البيضاء - سطات",
  "Oualidia": "الدار البيضاء - سطات",
  "Sidi Abbad": "الدار البيضاء - سطات",
  "Oulad Frej": "الدار البيضاء - سطات",
  "Zaouit Sidi Smail": "الدار البيضاء - سطات",
  "Jorf Lasfar": "الدار البيضاء - سطات",
  "Tnine Gharbia": "الدار البيضاء - سطات",
  "Sidi Abderrazzak Khzazna": "الدار البيضاء - سطات",
  "Oulad Amrane": "الدار البيضاء - سطات",
  "Moulay Abellah Amghar": "الدار البيضاء - سطات",
  "Sidi Ali Azemmour": "الدار البيضاء - سطات",
  "Oulad Ghanem": "الدار البيضاء - سطات",
  "Arba Aounate": "الدار البيضاء - سطات",
  "Chellalat": "الدار البيضاء - سطات",
  "Sidi Hajjaj": "الدار البيضاء - سطات",
  "Ouled Mrah": "الدار البيضاء - سطات",
  "El Gara": "الدار البيضاء - سطات",
  "El Mansouria": "الدار البيضاء - سطات",
  "El Borouj": "الدار البيضاء - سطات",
  "Zenata": "الدار البيضاء - سطات",
  "Sidi Rahal": "الدار البيضاء - سطات",
  "Tamaris": "الدار البيضاء - سطات",
  "Louizia": "الدار البيضاء - سطات",
  "Marrakech": "مراكش - آسفي",
  "Ait Ourir": "مراكش - آسفي",
  "Tahannaout": "مراكش - آسفي",
  "Tameslohte": "مراكش - آسفي",
  "Ben Guerir": "مراكش - آسفي",
  "El Kelaa des Sraghna": "مراكش - آسفي",
  "Chichaoua": "مراكش - آسفي",
  "imintanoute": "مراكش - آسفي",
  "Youssoufia": "مراكش - آسفي",
  "Tamansourt": "مراكش - آسفي",
  "Souihla": "مراكش - آسفي",
  "Chouiter": "مراكش - آسفي",
  "Sidi Abdellah Ghiat": "مراكش - آسفي",
  "OUDAYA Marrakech": "مراكش - آسفي",
  "Sid L Mokhtar": "مراكش - آسفي",
  "Tamellalt": "مراكش - آسفي",
  "Belaaguid": "مراكش - آسفي",
  "Mejjat - Marrakech": "مراكش - آسفي",
  "Sidi Bou Othmane": "مراكش - آسفي",
  "El Attaouia": "مراكش - آسفي",
  "Echemmaia": "مراكش - آسفي",
  "Skhour Rehamna": "مراكش - آسفي",
  "Mzoudia": "مراكش - آسفي",
  "Ouahat Sidi Brahim": "مراكش - آسفي",
  "Sid Zouine": "مراكش - آسفي",
  "Ourika": "مراكش - آسفي",
  "Lalla Takerkoust": "مراكش - آسفي",
  "Amizmiz": "مراكش - آسفي",
  "Tassoultante": "مراكش - آسفي",
  "OULED BEN RAHMOUN": "مراكش - آسفي",
  "Gouassem": "مراكش - آسفي",
  "Asni": "مراكش - آسفي",
  "Ouidane MARRAKECH": "مراكش - آسفي",
  "OULAD HASSOUN": "مراكش - آسفي",
  "Nzalat Laadam": "مراكش - آسفي",
  "Sebt Saiss": "مراكش - آسفي",
  "Moulay Brahim": "مراكش - آسفي",
  "Douar Sidi Moussa": "مراكش - آسفي",
  "Oulad yahya": "مراكش - آسفي",
  "Douar Soultan": "مراكش - آسفي",
  "Douar Bouazza": "مراكش - آسفي",
  "Chrifia": "مراكش - آسفي",
  "loudaya": "مراكش - آسفي",
  "Safi": "مراكش - آسفي",
  "Sebt Gzoula": "مراكش - آسفي",
  "Jamaat shaim": "مراكش - آسفي",
  "Hrara Safi": "مراكش - آسفي",
  "Had Hrara- Safi": "مراكش - آسفي",
  "Sidi Bouzid SAFI": "مراكش - آسفي",
  "Essaouira": "مراكش - آسفي",
  "Ghazoua": "مراكش - آسفي",
  "Douar Laareb": "مراكش - آسفي",
  "Sidi Kaouki": "مراكش - آسفي",
  "Ounagha": "مراكش - آسفي",
  "Al Morabitin": "مراكش - آسفي",
  "Kchoula": "مراكش - آسفي",
  "Smimou": "مراكش - آسفي",
  "Ait Said": "مراكش - آسفي",
  "Bizdad": "مراكش - آسفي",
  "Meskala": "مراكش - آسفي",
  "Mejji": "مراكش - آسفي",
  "Had Draa": "مراكش - آسفي",
  "Tidzi": "مراكش - آسفي",
  "Sidi Boulaalam": "مراكش - آسفي",
  "Boulaalam": "مراكش - آسفي",
  "Birkouate": "مراكش - آسفي",
  "Lwaiha": "مراكش - آسفي",
  "Faj Errih": "مراكش - آسفي",
  "Kraymat": "مراكش - آسفي",
  "Mramer": "مراكش - آسفي",
  "Tafetachte": "مراكش - آسفي",
  "Tamanar": "مراكش - آسفي",
  "Talmest": "مراكش - آسفي",
  "El Hrarta": "مراكش - آسفي",
  "El Hanchane": "مراكش - آسفي",
  "Beni Mellal": "بني ملال - خنيفرة",
  "Ougmas": "بني ملال - خنيفرة",
  "Sidi Jaber": "بني ملال - خنيفرة",
  "Oulad Ayad": "بني ملال - خنيفرة",
  "Timoulilte": "بني ملال - خنيفرة",
  "Azilal": "بني ملال - خنيفرة",
  "Aguelmous": "بني ملال - خنيفرة",
  "Oued Zem": "بني ملال - خنيفرة",
  "Kasba Tadla": "بني ملال - خنيفرة",
  "Ouled Nemma": "بني ملال - خنيفرة",
  "Ouled Mbarek": "بني ملال - خنيفرة",
  "Khenifra": "بني ملال - خنيفرة",
  "Khouribga": "بني ملال - خنيفرة",
  "Tighssaline": "بني ملال - خنيفرة",
  "Bejaad": "بني ملال - خنيفرة",
  "El Ksiba - Beni-Mellal": "بني ملال - خنيفرة",
  "Ighrem Laalam": "بني ملال - خنيفرة",
  "Fquih Ben Salah": "بني ملال - خنيفرة",
  "Oulad zmam": "بني ملال - خنيفرة",
  "Dar Ould Zidouh": "بني ملال - خنيفرة",
  "Sidi Aissa Ben Ali": "بني ملال - خنيفرة",
  "Bni Ayat": "بني ملال - خنيفرة",
  "Mrirt": "بني ملال - خنيفرة",
  "Ait Ishaq": "بني ملال - خنيفرة",
  "Laayayta - Beni Mellal": "بني ملال - خنيفرة",
  "Ouaouizeght": "بني ملال - خنيفرة",
  "Ouaoumana": "بني ملال - خنيفرة",
  "Oulad Yaich": "بني ملال - خنيفرة",
  "Oulad Youssef - Beni Mellal": "بني ملال - خنيفرة",
  "Ikhourba": "بني ملال - خنيفرة",
  "Oulad Ali - Beni Mellal": "بني ملال - خنيفرة",
  "Foum Oudi - Beni Mellal": "بني ملال - خنيفرة",
  "Kahf Nsour": "بني ملال - خنيفرة",
  "Dar Oulad Zidouh": "بني ملال - خنيفرة",
  "Ahl Merbaa - Beni Mellal": "بني ملال - خنيفرة",
  "Ahl Souss - Beni Mellal": "بني ملال - خنيفرة",
  "Ain El Ghazi Ali - Beni Mellal": "بني ملال - خنيفرة",
  "Ait Attab": "بني ملال - خنيفرة",
  "Ait Tislit": "بني ملال - خنيفرة",
  "Aourir - Beni Mellal": "بني ملال - خنيفرة",
  "Bir Mezoui": "بني ملال - خنيفرة",
  "El Bazzaza": "بني ملال - خنيفرة",
  "El Kbab": "بني ملال - خنيفرة",
  "Faryata": "بني ملال - خنيفرة",
  "Foum El Anser": "بني ملال - خنيفرة",
  "Foum Jamaa": "بني ملال - خنيفرة",
  "Foum Zaouia": "بني ملال - خنيفرة",
  "Had Bouhsousen": "بني ملال - خنيفرة",
  "Ikhoureba - Beni Mellal": "بني ملال - خنيفرة",
  "Kahf Nssoure": "بني ملال - خنيفرة",
  "Laajana": "بني ملال - خنيفرة",
  "Laayayta Oulad Gnaou": "بني ملال - خنيفرة",
  "Lahlalma": "بني ملال - خنيفرة",
  "Lakraza Ouled Said": "بني ملال - خنيفرة",
  "Mghila - Beni Mellal": "بني ملال - خنيفرة",
  "Moulay Bouaza": "بني ملال - خنيفرة",
  "Oulad Ali Loued": "بني ملال - خنيفرة",
  "Oulad Moussa - Beni Mellal": "بني ملال - خنيفرة",
  "Ouled Rguiaa": "بني ملال - خنيفرة",
  "Ouzoud - Beni Mellal": "بني ملال - خنيفرة",
  "Riad Salam-Beni Mellal": "بني ملال - خنيفرة",
  "Tanant": "بني ملال - خنيفرة",
  "Tifrit - Beni Mellal": "بني ملال - خنيفرة",
  "Tighasaline": "بني ملال - خنيفرة",
  "Zone Industriell - Beni Mellal": "بني ملال - خنيفرة",
  "Zouair": "بني ملال - خنيفرة",
  "Ouled Said El Oued": "بني ملال - خنيفرة",
  "Kaf Nsour": "بني ملال - خنيفرة",
  "Hattane": "بني ملال - خنيفرة",
  "Boujniba": "بني ملال - خنيفرة",
  "Boulanouare": "بني ملال - خنيفرة",
  "Ouled Driss - Beni Mellal": "بني ملال - خنيفرة",
  "Al Khalfia": "بني ملال - خنيفرة",
  "Oulad ismail - Beni Mellal": "بني ملال - خنيفرة",
  "Ait Ali": "بني ملال - خنيفرة",
  "Ait Rbaa": "بني ملال - خنيفرة",
  "Tanougha": "بني ملال - خنيفرة",
  "Adouz - Beni Mellal": "بني ملال - خنيفرة",
  "Aghbalou Ncerdan": "بني ملال - خنيفرة",
  "Ouled Moussa": "بني ملال - خنيفرة",
  "El Borj - Khenifra": "بني ملال - خنيفرة",
  "Lahri - khenifra": "بني ملال - خنيفرة",
  "Demnate": "بني ملال - خنيفرة",
  "Afourar": "بني ملال - خنيفرة",
  "Zaouiat Cheikh": "بني ملال - خنيفرة",
  "El Kebab": "بني ملال - خنيفرة",
  "Tagzert": "بني ملال - خنيفرة",
  "Souk El Had Des Bradia": "بني ملال - خنيفرة",
  "Souk Sebt Oulad Nemma": "بني ملال - خنيفرة",
  "Tachrafat": "بني ملال - خنيفرة",
  "Agadir": "سوس - ماسة",
  "Aglou": "سوس - ماسة",
  "Ait Amira": "سوس - ماسة",
  "Ait Baha": "سوس - ماسة",
  "Ait melloul": "سوس - ماسة",
  "Anza": "سوس - ماسة",
  "Aourir": "سوس - ماسة",
  "Belfaa": "سوس - ماسة",
  "Biougra": "سوس - ماسة",
  "Aoulouz": "سوس - ماسة",
  "Houara": "سوس - ماسة",
  "Imi Ouaddar": "سوس - ماسة",
  "Inchaden": "سوس - ماسة",
  "Inezgane": "سوس - ماسة",
  "Dcheira": "سوس - ماسة",
  "Tikiouine": "سوس - ماسة",
  "Drarga": "سوس - ماسة",
  "Lagfifat": "سوس - ماسة",
  "Kasbah El Taher": "سوس - ماسة",
  "Massa": "سوس - ماسة",
  "Oulad Berhil": "سوس - ماسة",
  "Oulad Dahou": "سوس - ماسة",
  "Sebt El Guerdane": "سوس - ماسة",
  "Sidi bibi": "سوس - ماسة",
  "Temsia": "سوس - ماسة",
  "Taroudant": "سوس - ماسة",
  "Tarrast": "سوس - ماسة",
  "TATA": "سوس - ماسة",
  "Tin Mansour": "سوس - ماسة",
  "Tiznit": "سوس - ماسة",
  "Bounaamane - Tiznit": "سوس - ماسة",
  "Oulad Teima": "سوس - ماسة",
  "Akka": "سوس - ماسة",
  "Fam El Hisn": "سوس - ماسة",
  "Foum zguid": "سوس - ماسة",
  "Tissint": "سوس - ماسة",
  "Akka Ighane": "سوس - ماسة",
  "Tafraoute": "سوس - ماسة",
  "Taghazout": "سوس - ماسة",
  "Taliouine": "سوس - ماسة",
  "Tamraght": "سوس - ماسة",
  "Taddart - Agadir": "سوس - ماسة",
  "Oujda": "الشرق",
  "NADOR": "الشرق",
  "Beni Ensar": "الشرق",
  "Selouane": "الشرق",
  "Jaadar": "الشرق",
  "Zeghanghane": "الشرق",
  "Segangan": "الشرق",
  "AFRA": "الشرق",
  "Al Aaroui": "الشرق",
  "Bouarg": "الشرق",
  "Mariouari": "الشرق",
  "Barichino": "الشرق",
  "Tiztoutine": "الشرق",
  "Beni Chiker": "الشرق",
  "Farkhana": "الشرق",
  "Beni Sidal Jbel": "الشرق",
  "Kariat Arekmane": "الشرق",
  "Zaio": "الشرق",
  "Ouled Settout": "الشرق",
  "Driouch": "الشرق",
  "Ben Taieb": "الشرق",
  "Tafersit": "الشرق",
  "Midar": "الشرق",
  "Kassita": "الشرق",
  "Telat Azlaf": "الشرق",
  "Tamsamane": "الشرق",
  "Boudinar": "الشرق",
  "Dar El Kebdani": "الشرق",
  "Berkane": "الشرق",
  "AHFIR": "الشرق",
  "Ain Erreggada": "الشرق",
  "Ain Reggada": "الشرق",
  "Aklim": "الشرق",
  "Boughriba": "الشرق",
  "Madagh": "الشرق",
  "SAAIDIA": "الشرق",
  "Saidia": "الشرق",
  "Beni Drar": "الشرق",
  "Jerada": "الشرق",
  "Ain Beni Mathar": "الشرق",
  "Tendrara": "الشرق",
  "Bouarfa": "الشرق",
  "Figuig": "الشرق",
  "Laayoune Charkia": "الشرق",
  "El Aioun Sidi Mellouk": "الشرق",
  "Taourirt": "الشرق",
  "Guercif": "الشرق",
  "Tafoughalt": "الشرق",
  "Ras El Ma - Nador": "الشرق",
  "SOUK EL GOUR": "الشرق",
  "Tandit": "الشرق",
  "Errachidia": "درعة - تافيلالت",
  "Ouarzazate": "درعة - تافيلالت",
  "Tinghir": "درعة - تافيلالت",
  "Zagora": "درعة - تافيلالت",
  "Midelt": "درعة - تافيلالت",
  "Agdz": "درعة - تافيلالت",
  "Nkoub Zagora": "درعة - تافيلالت",
  "Tazarine": "درعة - تافيلالت",
  "Boumaln dads": "درعة - تافيلالت",
  "Alnif": "درعة - تافيلالت",
  "Kelaat MGouna": "درعة - تافيلالت",
  "Tazenakht": "درعة - تافيلالت",
  "Taznakht": "درعة - تافيلالت",
  "Boudnib": "درعة - تافيلالت",
  "Marzouga": "درعة - تافيلالت",
  "Zaida": "درعة - تافيلالت",
  "Tinejdad": "درعة - تافيلالت",
  "Rissani": "درعة - تافيلالت",
  "Riche": "درعة - تافيلالت",
  "Boumia": "درعة - تافيلالت",
  "Erfoud": "درعة - تافيلالت",
  "Goulmima - Errachidia": "درعة - تافيلالت",
  "Aoufous": "درعة - تافيلالت",
  "Msemrir tinghir": "درعة - تافيلالت",
  "Gourrama": "درعة - تافيلالت",
  "Imilchil": "درعة - تافيلالت",
  "Tagounite‬ zagora": "درعة - تافيلالت",
  "Tamzmout": "درعة - تافيلالت",
  "Guelmim": "كلميم - واد نون",
  "SIDI IFNI": "كلميم - واد نون",
  "Mirleft": "كلميم - واد نون",
  "Bouizakarne": "كلميم - واد نون",
  "TANTAN": "كلميم - واد نون",
  "El Ouatia TAN TAN": "كلميم - واد نون",
  "Assa": "كلميم - واد نون",
  "Zag": "كلميم - واد نون",
  "Laayoune Sahara": "العيون - الساقية الحمراء",
  "laayoune Port": "العيون - الساقية الحمراء",
  "EL MARSA LAAYOUNE": "العيون - الساقية الحمراء",
  "Boujdour": "العيون - الساقية الحمراء",
  "Essmara SAHARA": "العيون - الساقية الحمراء",
  "Smara": "العيون - الساقية الحمراء",
  "Tarfaya": "العيون - الساقية الحمراء",
  "AKHFNIR": "العيون - الساقية الحمراء",
  "Dakhla": "الداخلة - وادي الذهب",
};

function foldOfficialCity(text: string) {
  return (text || "")
    .normalize("NFKD")
    .replace(/\u202c/g, "")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/-/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const FOLDED_TO_REGION: Record<string, string> = {};
for (const [city, region] of Object.entries(CITY_TO_REGION)) {
  const folded = foldOfficialCity(city);
  if (folded) FOLDED_TO_REGION[folded] = region;
}

export function getRegionForCity(cityName: string) {
  if (!cityName) return UNKNOWN_REGION;
  const key = cityName.trim();
  if (CITY_TO_REGION[key]) return CITY_TO_REGION[key];
  return FOLDED_TO_REGION[foldOfficialCity(key)] || UNKNOWN_REGION;
}

export function regionIdForOfficialCity(city: string) {
  const name = getRegionForCity(city);
  return REGION_NAME_TO_ID[name] || "";
}
